# Generated by Django 5.0.3 on 2025-11-03 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=128)),
                ('name_kg', models.CharField(max_length=128, null=True)),
                ('name_en', models.CharField(max_length=128, null=True)),
                ('left_ordering', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('right_ordering', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category/original_images/')),
                ('resized_image', models.ImageField(blank=True, null=True, upload_to='category/resized_images/')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'category',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=128)),
                ('name_kg', models.CharField(max_length=128, null=True)),
                ('name_en', models.CharField(max_length=128, null=True)),
                ('description', models.TextField()),
                ('recommended', models.BooleanField(default=False)),
                ('recommended_left_side', models.BooleanField(default=False)),
                ('bestsellers', models.BooleanField(default=False)),
                ('promotional', models.BooleanField(default=False)),
                ('characteristics', models.JSONField(null=True)),
                ('code_name', models.CharField(max_length=32, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'product',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/original_images/')),
                ('resized_image', models.ImageField(blank=True, null=True, upload_to='products/resized_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product')),
            ],
            options={
                'verbose_name': 'Изображения товара',
                'verbose_name_plural': 'Изображения товаров',
                'db_table': 'product_image',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.JSONField()),
                ('size', models.CharField(max_length=32)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('discount_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='product.product')),
            ],
            options={
                'verbose_name': 'Детали продукта',
                'verbose_name_plural': 'Детали продуктов',
                'db_table': 'product_variant',
                'ordering': ['-id'],
            },
        ),
    ]
